### ISSUE TITLE
week01 回覆

### ISSUE THREAD

**Issue by azole** [Bozheng0/git-practice#1]
不錯，最後也有附上連結，但跟你確認一下，這些圖片是你自己畫的嗎？不是的話要附上引用來源喔。

![image](https://github.com/user-attachments/assets/28f75464-e2d7-4e2b-942a-8fb1e28cd613)

**Comment by Bozheng0** [comment]
圖片是引用網路上的，有放在參考資源中，也在圖片正下方補上連結了。

**Comment by azole** [comment]
ok 那如果沒有其他要討論的部分，這個 issue 可以 close 了
